services:
  wakemae:
    image: ghcr.io/ei-sugimoto/wakemae:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config.yml:/etc/wakemae/config.yml
    networks:
      wakemae_network:
        ipv4_address: 172.20.0.10
  
  web1:
    image: nginx:latest
    ports:
      - 8080:80
    labels:
      wakemae.domain: web1.docker
    dns:
      - 172.20.0.10
    networks:
      wakemae_network:
        ipv4_address: 172.20.0.11
    depends_on:
      - wakemae

  web2:
    image: nginx:latest
    ports:
      - 8081:80
    labels:
      wakemae.domain: web2.docker
    dns:
      - 172.20.0.10
    networks:
      wakemae_network:
        ipv4_address: 172.20.0.12
    depends_on:
      - wakemae

networks:
  wakemae_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16